# Generated by Django 2.2.12 on 2022-07-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckSuma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directorio', models.CharField(max_length=80)),
                ('hashsuma', models.CharField(max_length=80)),
            ],
        ),
    ]
